#!/bin/sh -e
#
#  cyrus-makedirs  -  Parses a Cyrus imap.d configuration file, and creates
#                     the correct directory trees for all partitions
#
#  Copyright 2001,2002 by Henrique de Moraes Holschuh <hmh@debian.org.
#  Released under the terms of the GNU General Public License (GPL) version 2
#
# $Id: cyrus-makedirs 793 2009-09-03 09:35:11Z sven $

# See lib/util.c, dir_hash_c for Cyrus' directory hashing
# for the new hash style
#HASHDIRS="A B C D E F G H I J K L M N O P Q R S T U V W"
# for the old hash style
HASHDIRS="a b c d e f g h i j k l m n o p q r s t u v w x y z"

# Sane locale, please
LC_ALL=C
export LC_ALL

CYRUSOPTFILESYS=1
IMAPD_CONFIG=/etc/imapd.conf

if [ -f /etc/sysconfig/cyrus-imapd ]; then
    SYSCONF=/etc/sysconfig/cyrus-imapd
    . /etc/sysconfig/cyrus-imapd
elif [ -f /etc/default/cyrus-imapd ]; then
    SYSCONF=/etc/default/cyrus-imapd
    . /etc/default/cyrus-imapd
fi

getconf () {
	confvalue=`sed --silent -e "/^[[:blank:]]*$1:/ { \
	s#^[[:blank:]]*$1:[[:blank:]]*## \
	p
	}" < "$IMAPD_CONFIG" | head -1`
	result=${confvalue:-$2}
}

killsquat=0
[ "$1" = "--cleansquat" ] && {
	killsquat=1
	shift
}


IMAPD_CONFIG="${1:-$IMAPD_CONFIG}"
[ -r "$IMAPD_CONFIG" ] || {
	echo $0: unable to read configuration file $IMAPD_CONFIG. Aborting...
	exit 1
}

getconf configdirectory /var/lib/imap
confdir="$result"
[ -d "$confdir" ] || {
	echo $0: $confdir is not an directory. Aborting...
	exit 2
}

getconf sievedir /var/lib/imap/sieve
sievedir="$result"

getconf sieveusehomedir 0
case "$result" in
	1|t|true|yes|on) nosievedir=1
			;;
	*)		nosievedir=0
			;;
esac

getconf hashimapspool 0
case "$result" in
	1|t|true|yes|on) hashspool=1
			;;
	*)		hashspool=0
			;;
esac

# Partitions list
partitions=`sed --silent -e "/^[[:blank:]]*partition-[[:alnum:]]\+:/ { \
            s#^[[:blank:]]*partition-[[:alnum:]]\+:[[:blank:]]*## \
	    p
	    } " < "$IMAPD_CONFIG" | sort | uniq | xargs`

# First, fix up the entire confdir subtree
echo "Creating/updating cyrus control directories in ${confdir}..."
[ -d "$confdir" ] || mkdir -p "$confdir"
chmod 751 "$confdir"
for i in db proc socket log msg user quota; do
    [ -d "$confdir/$i" ] || mkdir -p "$confdir/$i"
    chmod 700 "$confdir/$i"
done
chmod 751 $confdir/socket
for i in user quota ; do
    for j in $HASHDIRS ; do
    	[ -d "$confdir/$i/$j" ] || mkdir "$confdir/$i/$j"
    done
done
find "$confdir" \( -not -user cyrus -or  -not -group mail \) -print0 | xargs -r -0 chown cyrus:mail

# Now, create the spool partitions
for i in $partitions ; do
	echo "Creating/updating partition spool $i..."
	[ -d "$i" ] || mkdir -p "$i"
	chmod 750 "$i"
	[ $hashspool -eq 1 ] && {
	   for j in $HASHDIRS ; do
	        [ -d "$i/$j" ] || mkdir "$i/$j"
	   done
	}
	[ -d "$i/stage." ] || mkdir "$i/stage."
	find "$i" \( -not -user cyrus -or  -not -group mail \) -print0 | xargs -r -0 chown cyrus:mail
	# and kill any squatter indexes
	[ $killsquat -ne 0 ] && find "$i" -name 'cyrus.squat' -type f -print0 | xargs -r -0 rm -f
done

# And the sieve directory structure
[ $nosievedir -eq 0 ] && {
	[ -d "$sievedir" ] || mkdir "$sievedir"
	chmod 755 "$sievedir"
	for j in $HASHDIRS ; do
		[ -d "$sievedir/$j" ] || mkdir "$sievedir/$j"
		chmod 755 "$sievedir/$j"
	done
	find "$sievedir" \( -not -user cyrus -or  -not -group mail \) -print0 | xargs -r -0 chown cyrus:mail
}

[ "x${CYRUSOPTFILESYS}" != "x1" ] && exit 0
#
# Fix attributes for every partition
#
# ext2:  Don't use ext2 for Cyrus spools. But if you must, enable Sync writes
# ext3:  Journal data too, since that improves access time a LOT
#        (maybe in the future, there's a bug in 2.4.18 ext3 w/ +j)
#
echo "Trying to optimize Cyrus partitions, edit $SYSCONF to disable..."

partsys="${confdir} ${partitions}"
filesys=`df -P -T ${partsys} | sed -e "1 d" -e "s/ \+/ /g" | cut -d " " -f 2 | xargs`
for i in ${filesys} ; do
	case ${i} in
	ext2)
  		echo "Setting attributes to +S for  ${partsys%% *}..."
		find "${partsys%% *}" -type d -print0 | xargs -r -0 chattr +S
		;;
	ext3)
  		echo "Setting attributes to -S -j for  ${partsys%% *}..."
		find "${partsys%% *}" -type d -print0 | xargs -r -0  chattr -S -j
		;;
	esac
	partsys="${partsys#* }"
done

exit 0
