#!/bin/sh

set -e

fixperms() {
    group=$(getent group roundcube_sysgroup >/dev/null 2>&1 && echo "roundcube_sysgroup" || echo "adm")
    user=$(getent passwd roundcube_sysuser >/dev/null 2>&1 && echo "roundcube_sysuser" || echo "www-data")
    chown -R ${user}:${group} \
        /var/cache/chwala \
        /var/lib/chwala \
        /var/log/chwala
    chmod 750 \
        /var/cache/chwala \
        /var/lib/chwala \
        /var/log/chwala
}

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}

update_database() {
    /usr/share/roundcubemail/bin/updatedb.sh \
        --dir /usr/share/doc/chwala/SQL/ \
        --package chwala \
        >/dev/null 2>&1 || :
}


case "$1" in
    configure)
        fixperms
        update_database
        a2enmod rewrite >/dev/null 2>&1 || true

        if [ -f "/etc/plesk-release" ]; then
            exit 0
        fi

        if [ -e "/etc/apache2/sites-available/chwala.conf" -a ! -e "/etc/apache2/sites-enabled/chwala.conf" ]; then
            a2ensite chwala.conf
        fi
        reload_apache reload
    ;;
esac

exit 0
