#!/bin/bash
#

filter_csv() {
    echo -n "$1" | tr "," "\n" | egrep -v "^($2)\$" | egrep -v '^$' | tr "\n" "," | sed -e 's/,$//'
}

if [ -f "/usr/share/univention-lib/all.sh" ]; then
    . /usr/share/univention-lib/all.sh
    eval "$(ucr shell)"

    if [ "$1" = "remove" ] ; then

        # Remove the kolab3.schema copy
        if [ -f "/etc/ldap/schema/kolab3.schema" ]; then
            rm -rvf /etc/ldap/schema/kolab3.schema
        fi
        if [ -f "/etc/ldap/schema/univention-kolab3-wrapper.schema" ]; then
            rm -rvf /etc/ldap/schema/univention-kolab3-wrapper.schema
        fi

        if is_ucr_true "ldap/index/autorebuild" ; then
            filtered_ldap_index_eq="$(filter_csv "$ldap_index_eq" "alias")"
            filtered_ldap_index_pres="$(filter_csv "$ldap_index_pres" "alias")"
            filtered_ldap_index_approx="$(filter_csv "$ldap_index_approx" "alias")"

            /etc/init.d/slapd stop
            univention-config-registry set ldap/index/eq="$filtered_ldap_index_eq" \
                                           ldap/index/pres="$filtered_ldap_index_pres" \
                                           ldap/index/approx="$filtered_ldap_index_approx"
            # run slapindex and selectively filter out this unsettling warning from stderr
            { /usr/sbin/slapindex  2>&1 >&3 | sed -e "/Runnig as root\!/,/There's a fair chance slapd will fail to start./d" >&2; } 3>&1

            /etc/init.d/slapd start
        else
            grep -q crestart /etc/init.d/slapd && /etc/init.d/slapd crestart || true
        fi
    fi

fi
exit 0

