<?php

require_once 'JsonSchema/autoload.php';
require_once 'Composer/CaBundle/autoload.php';
require_once 'Composer/Semver/autoload.php';
require_once 'Composer/Spdx/autoload.php';
require_once 'Seld/JsonLint/autoload.php';
require_once 'Symfony/Component/Console/autoload.php';
require_once 'Symfony/Component/Finder/autoload.php';
require_once 'Symfony/Component/Process/autoload.php';
require_once 'Symfony/Component/Filesystem/autoload.php';
require_once 'Seld/CliPrompt/autoload.php';
require_once 'Psr/Log/autoload.php';

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                ___CLASSLIST___
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require ___BASEDIR___$classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
